<?php

return [
    [
        'label' => 'Dashboard',
        'route' => 'dashboard',
        'icon' => 'icon-home4',
        'submenu' => [],
        'childs' => [],
        'activity' => ['read'],
    ], [
        'label' => 'Akses',
        'route' => 'access',
        'icon' => 'icon-accessibility2',
        'submenu' => [
            [
                'label' => 'Akun',
                'route' => 'account',
                'icon' => 'icon-user',
                'submenu' => [],
                'childs' => ['account-entry'],
                'activity' => ['read', 'create', 'edit', 'delete', 'reset_password'],
            ], [
                'label' => 'Peran',
                'route' => 'role',
                'icon' => 'icon-accessibility',
                'param' => [],
                'childs' => ['role-entry'],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ],
        ],
    ], [
        'label' => 'Master',
        'route' => 'master',
        'icon' => 'icon-stack2',
        'submenu' => [
            [
                'label' => 'Kategori',
                'route' => 'category',
                'icon' => 'icon-stack-text',
                'submenu' => [],
                'childs' => ['category-entry'],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ], [
                'label' => 'Lokasi',
                'route' => 'location',
                'icon' => 'icon-stack-text',
                'submenu' => [],
                'childs' => ['location-entry'],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ], [
                'label' => 'Perusahaan',
                'route' => 'company',
                'icon' => 'icon-stack-text',
                'submenu' => [],
                'childs' => ['company-entry'],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ], 
            [
                'label' => 'Barang',
                'route' => 'asset_data',
                'icon' => 'icon-home4',
                'submenu' => [],
                'childs' => ['asset_data-entry'],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ], 
            // [
            //     'label' => 'Status Asset',
            //     'route' => 'asset_status',
            //     'icon' => 'icon-stack-text',
            //     'submenu' => [],
            //     'childs' => ['asset_status-entry'],
            //     'activity' => ['read', 'create', 'edit', 'delete'],
            // ],
        ],
    ], 
    [
        'label' => 'Penggunaan',
        'route' => 'penggunaan',
        'icon' => 'icon-home4',
        'submenu' => [],
        'childs' => ['penggunaan-entry'],
        'activity' => ['read', 'create', 'edit', 'delete'],
    ],
    // [
    //     'label' => 'Pustaka Media',
    //     'route' => 'media-library',
    //     'icon' => 'icon-media',
    //     'submenu' => [
    //         [
    //             'label' => 'Gambar',
    //             'route' => 'image',
    //             'icon' => 'icon-image3',
    //             'param' => ['type' => 'image'],
    //             'childs' => [],
    //             'activity' => ['read', 'create', 'delete'],
    //         ], [
    //             'label' => 'Video',
    //             'route' => 'video',
    //             'icon' => 'icon-video-camera',
    //             'param' => ['type' => 'video'],
    //             'childs' => [],
    //             'activity' => ['read', 'create', 'delete'],
    //         ], [
    //             'label' => 'File',
    //             'route' => 'application',
    //             'icon' => 'icon-file-text',
    //             'param' => ['type' => 'application'],
    //             'childs' => [],
    //             'activity' => ['read', 'create', 'delete'],
    //         ], [
    //             'label' => 'Audio',
    //             'route' => 'audio',
    //             'icon' => 'icon-music',
    //             'param' => ['type' => 'audio'],
    //             'childs' => [],
    //             'activity' => ['read', 'create', 'delete'],
    //         ],
    //     ],
    // ], 
    [
        'label' => 'Pengaturan',
        'route' => 'setting',
        'icon' => 'icon-gear',
        'submenu' => [
            [
                'label' => 'Umum',
                'route' => 'desc-site',
                'icon' => 'icon-file-text2',
                'param' => [],
                'childs' => [],
                'activity' => ['read', 'edit'],
            ], [
                'label' => 'Profil',
                'route' => 'profil',
                'icon' => 'icon-user',
                'param' => [],
                'childs' => [],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ], [
                'label' => 'Penanganan Gambar',
                'route' => 'handle-image',
                'icon' => 'icon-crop2',
                'param' => [],
                'childs' => ['handle-image-entry'],
                'activity' => ['read', 'create', 'edit', 'delete'],
            ], [
                'label' => 'Log',
                'route' => 'log',
                'icon' => 'icon-crop2',
                'param' => [],
                'childs' => [],
                'activity' => ['read'],
            ],
        ],
    ],
];
